### ISSUE TITLE
Duvida 

### ISSUE THREAD

**Issue by andrec762** [az19djsd9823ui23/web-back-end#2]
Estou tentando configurar o webserver na minha maquina porém estou encontrando dificuldades na configuração. Ao executar o comando python manage.py migrate estou recebendo o seguinte erro:

Traceback (most recent call last):
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 8458?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/trabalho/Webbackend/web-back-end/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 8458?

O erro provavelmente é devido ao arquivo .env não configurado só que estou em duvidas como o configuro ? Não entendi muito bem o que precisa ser feito no mesmo, além disso o mesmo deve ficar na pasta arbitrage ou deve ser movido para outra pasta ?

**Comment by joaoderocha** [comment]
o .env deve ser modificado da seguinte maneira:
DEBUG=on # opcao de debug, caso verdadeiro os erros que as paginas gerarem seram detalhados ao invez das paginas padroes, 404, 500, etc.
SECRET_KEY = your-secret-key # esta chave deve ser a chave que se utiliza no banco de dados para fazer o login com algum usuario.
DATABASE_URL=psql://urser:un-githubbedpassword@127.0.0.1:8458/database # nesta linha temos varios parametros. podemos dividi-la dessa forma DATABASE_URL={param1}://{param2}:{param3}@{param4}:{param5}/{param6}
param1 = a sigla do banco de dados deseja utilizar.
param2 = usuario do banco de dados
param3 = senha do banco de dados
param4 = ip de onde esta o banco de dados
param5 = porta que o banco de dados esta conectado
param6 = o nome que voce criou para o seu banco de dados
SQLITE_URL=sqlite:///my-local-sqlite.db # esta linha diz respeito ao banco de dados sqlite padrao do django. caso nao estiver utilizando pode comentar essa linha.
CACHE_URL=memcache://127.0.0.1:11211,127.0.0.1:11212,127.0.0.1:11213 # esta linha diz respeito ao path da cache do servidor. Nao modifique.
REDIS_URL=rediscache://127.0.0.1:6379/1?client_class=django_redis.client.DefaultClient&password=ungithubbed-secret # esta linha diz respeito tambem a configuracao a cache do servidor, nao modifique.


Sobre o erro acima, voce vai resolve-lo configurando corretamente o .env . Recomendo utilizar o mysql.

abracos

**Comment by andrec762** [comment]
Consegui aqui, obrigado pela explicação :D
